### ISSUE TITLE
Duplicate Search Results

### ISSUE THREAD

**Issue by lingrlongr** [stephenmcd/mezzanine#1205]
If you perform a search against a model using relative search_fields and more than one related object matches, you'll receive duplicate search results.  Example:

    class Section(Page):
        search_fields = ('block__content',)

    class Block(Orderable):
        page = models.ForeignKey(Section)
        content = RichTextField()

In this case, you'll see the same Section Page returned multiple times.

The fix I see is to modify `search()` in `mezzanine.core.views.py` with:

    results = list(set(results))

Does this fix seem appropriate?  If so I can submit a pull request.

**Comment by stephenmcd** [comment]
I can't reproduce this - in fact I believe this was an issue a long time ago that has already been resolved. 

Are you using a recent version of Mezzanine? Are you sure the Page isn't in the database twice?

The real fix would be to use an SQL `DISTINCT` clause, which is what we already do here: https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/managers.py#L143

In fact if I remove that call to `distinct()`, I can certainly reproduce the issue and get duplicate results using search fields that span related models.

So there's something else at play in your project - if you're pressed for time you can easily apply your fix to your own project by overriding the search view inside your project with a copy of it using your patch, but I'd really appreciate you trying to find the root cause so that we can fix the issue if there is one, and prevent it from affecting anyone else.

To start with you might like to modify Mezzanine directly in your environment by going to that line I referred to above where `distinct()` is called, since that's a good spot to access the SQL queries being run, and print out the queries, something like: 

```
        print str(queryset.distinct().query)
        return queryset.distinct()
```

If your search spans multiple multiple models (say multiple Page types, not related models as we're discussing), then multiple queries will be run for a single search. Once you see the query/queries being printed, you can run them manually against your database - hopefully the results highlight the issue.

**Comment by lingrlongr** [comment]
Ah, yes.  An old version.  I'll have to try updating and see what I break.  I remember trying to using `distinct()`, but I think I was perhaps using it in the wrong spot.

**Comment by stephenmcd** [comment]
Awesome! Thanks for the update.

**Comment by lingrlongr** [comment]
Trying to upgrade now.  From 3.0.9 to 3.1.0.  Never did an upgrade before, so I'm expecting some errors especially with South...
