### ISSUE TITLE
Having two links to the same path: what should be the behavior?

### ISSUE THREAD

**Issue by acatton** [stephenmcd/mezzanine#1220]
Hi there,

This is hard to explain. I'll try to do my best:

I have an app which I plug to `/example/`:

```python
urlpatterns = patterns(
   url('^example/', include('example_app.urls')),
   # other mezzanine urls...
)
```

My base templates (which my `example_app` is using) has a top nav:
```html
<nav>
  {% page_menu "pages/menus/topnav.html" %}
</nav>
```

Now, in this top nav I want to link to `/example/page/`, so I create a new `Link` and set its url to `/example/page/`. But this need to be under "Example → Page", and "About Us → Page". So I have two links with the same `slug` in the Database.

So when I go to `/example/page/`, it tries to generate the menu, and [fails here](https://github.com/stephenmcd/mezzanine/blob/a3abfa6d8fc69c2f55a69836826e83c89ace9603/mezzanine/pages/templatetags/pages_tags.py#L59).

I feel confident in my ability and will to fix this problem. It's just that I don't know what should be the behavior here.

 * We could make every single link having the slug `/example/page/` be the current page here. But since I'm highlighting the current page, this would mean that the "Example" branch and the "About Us" branch would be "unfolded", and the two links would be highlighted.
 * We could randomly pick one. (I think this is a bad idea)
 * We could pick none of them. (And we wouldn't highlight any link)
 * Something else?

Is that a feature that we want? Does any one have any thought? @stephenmcd ?

**Comment by AlexHill** [comment]
I have a similar situation on my site. Where there is more than one candidate parent, I use a heuristic something like this:
* If the HTTP_REFERER (the URL the browser came from) begins with one parent's URL, pick that one. If both parents match, pick the longer substring. Conceptually the user is browsing within that subtree, so should stay there. Example: user came from ``/about/history/``, so the ``About Us`` branch should be unfolded.
* Otherwise, just pick the parent with the longest matching initial substring. Example: user arrived from Google, so the ``Example`` branch should be unfolded.
* Otherwise if no parent shares a common initial substring, just pick one in some deterministic way.

IMO this is the least surprising behaviour from a user's point of view. Let me know what you think.

Alex

**Comment by stephenmcd** [comment]
Sorry I don't understand what you're describing.

Are you saying you created a `Link` page that points to another page, so they end up with the same slug?

**Comment by acatton** [comment]
@stephenmcd yeah, it's actually very hard to explain.

As a user, what I did is creating two `Link`. And for both, set their URL to `/example/page/`. (I didn't put any scheme or domain.)

In the database the URL field is reflected by the `slug` field. I don't know if it makes sense?

**Comment by stephenmcd** [comment]
I've just pushed the fix which will resolve the bug - basically in the code that's failing, we shouldn't look at link pages, since they're not meant to represent an actual page of content on the site.

BTW you could also resolve the issue by creating a page that points to the root of the extra app, eg: "/example/".

**Comment by stephenmcd** [comment]
And thanks a lot for raising the issue!

**Comment by acatton** [comment]
@stephenmcd I was planning to fix it myself according to what you would have considered the most adequate behavior. But I think that works. Thanks for fixing it!
