### ISSUE TITLE
Error mezzanine with modeltranslation

### ISSUE THREAD

**Issue by Cajoline** [stephenmcd/mezzanine#1230]
Hi, 
I have a error when i try the new mezzanine version with modeltranslation, i have an existing project
and i want translating existing page, but i have this error message:

```
modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "Form"
```

Thank you, for you're help

**Comment by stephenmcd** [comment]
Any idea @Kniyl ?

**Comment by Cajoline** [comment]
I try with two diffrent project and i have the same error

**Comment by stephenmcd** [comment]
Presuming no one's able to help you, you might want to try creating a new project, and step by step introducing the components of your existing project, to try and isolate the error.

**Comment by stephenmcd** [comment]
You'll also need to provide some form of traceback - the above error really isn't enough to go by.

**Comment by Cajoline** [comment]
@stephenmcd  thank you , It's strange :) 
Ok, if @Kniyl has no idea either, I'll trying to do any tests

Thx

**Comment by miguelgr** [comment]
It´s because of the order of your INSTALLED_APPS in the settings file. 
Make sure  `mezzanine.pages` it´s the first one.

MEZZANINE_APPS = (
    "mezzanine.boot",
    "mezzanine.conf",
    "mezzanine.core",
    "mezzanine.pages",
    "mezzanine.generic",
    "mezzanine.blog",
    "mezzanine.forms",
    "mezzanine.galleries",
)

**Comment by stephenmcd** [comment]
That's great to know, thanks!

We might be able to make Mezzanine ensures that happens.

**Comment by stephenmcd** [comment]
I've just pushed a fix which ensures the pages app is first - it would be great if you could test this against your existing project to see if it resolves the issue.

Thanks again @miguelgr for the resolution.

**Comment by Cajoline** [comment]
Big thx @miguelgr and @stephenmcd, now it's work nice !
now just missing modeltranslation for cartridge :)

**Comment by Kniyl** [comment]
Sorry for comming late in the discussion. The solution is indeed to have mezzanine.page before any of its subclasses in INSTALLED_APPS. I made sure it is the case for new projects but didn't thought of a way to handle old ones.

That said, I was wondering if the modification of mezzanine.utils.conf wouldn't have some side effects. What happens when an app is placed before all of mezzanine ones in INSTALLED_APPS in order to provide alternate templates or static files. Won't this modification make mezzanine.page's static files and templates appear instead of the one of the custom app? Thus breaking the look and feel of the project?

**Comment by Kniyl** [comment]
What about : Kniyl/mezzanine@d2cbed6c39ed4bb4e00fbc1ec65eeaa01af5b7bd ?

**Comment by stephenmcd** [comment]
Thanks @Kniyl, you're right of course, this would break template overriding.

Even with your improved approach, wouldn't it mean mezzanine.pages gets moved above apps that might contain both Page subclasses, and templates intended to override templates in the pages app?

It seems like there's no real way around this other than moving all of the templates out of mezzanine.pages and into possibly mezzanine.core, even though they don't belong there.

**Comment by stephenmcd** [comment]
I've reverted the change from yesterday, and I'm honestly reluctant to move all of the templates from pages to core just to deal with this.

Perhaps we just need to document the app ordering requirements here in the new docs for multilingual content.

**Comment by Kniyl** [comment]
Since none of the the mezzanine apps that use models derived from Pages are overriding templates, I don't think it is up to mezzanine to handle that.

We can use my code to add a more explicit warning message instead of moving mezzanine.pages and let the users make their own design choices. This will help handle the transition for old projects.

As for theming apps that also define models with translation fields. I added a note in the documentation I proposed explaining that it might be splitted. Hope that is enough to make everything clear.
