### ISSUE TITLE
Missing Select Files button (swf not running)

### ISSUE THREAD

**Issue by allenwooky** [stephenmcd/mezzanine#1246]
When in Media Library and you need to upload files, the swf is not running. The same with when you want to edit html

**Comment by allenwooky** [comment]
POST /admin/media-library/upload_file/ HTTP/1.1" 302

**Comment by stephenmcd** [comment]
This is likely due to one of several things that could be wrong with your own environment - misconfigured settings, hosting of static files, something particular to your browser, I couldn't say for sure given the info you mentioned. It's been discussed on the mailing list before, I'd suggest searching there and if you have no luck, try posting a new request for help there.

Thanks!

**Comment by dpnova** [comment]
I stumbled on this... immediately i knew I didn't have flash running, so this seems relevant: https://stackoverflow.com/questions/5137093/uploadify-ruins-file-upload-when-no-flash-in-browser
