### ISSUE TITLE
mezzanine-project some-name-with-a.in-it causes import error

### ISSUE THREAD

**Issue by orotau** [stephenmcd/mezzanine#1248]
Edge case @jerivas 
If you put a dot '.' in the mezzanine project name the `python manage.py createdb` command falls over
There is a workaround namely `python manage.py createdb  --settings=settings`
`python manage.py runserver  --settings=settings` but then as soon as you go to the home page the site falls over....
g

**Comment by jerivas** [comment]
In general with Django, it's a bad idea to name your project with dots in
it. The reason is that Django and Mezzanine projects are simply Python
modules and Python uses dots everywhere to indicate hierarchy. When you
import something named "foo.bar", you're telling Python that there is a
"bar" module inside the "foo" module.

Current best practice is to go all lowercase and avoid all "joinery"
characters between words, or go with underscores. Avoid dashes, as they can
be interpreted as subtraction in Python code.

**Comment by stephenmcd** [comment]
Thanks guys, I thought this was checked for in the code when creating a project, but apparently not - pushing a fix.
