### ISSUE TITLE
Can I deploy my project on Webfaction?

### ISSUE THREAD

**Issue by superrandres** [stephenmcd/mezzanine#1274]
Sorry if my question is very basic, I'm from Ecuador, and I want to please help me know if you need to put in a folder configuration files of the project. I have always worked well, and not as MEZZANINE which puts them at the root.

**Comment by jerivas** [comment]
Hi Ronald, welcome to the Mezzanine community. For general questions like this, it is better if you post to the [mailing list](https://groups.google.com/forum/#!forum/mezzanine-users), instead of opening a new issue.

Regarding your question, I'm the author of [mezzanine-webf](https://github.com/jerivas/mezzanine-webf), a set of files for deploying Mezzanine to Webfaction. I'ts been a while since I actually used it, and I can't tell how well it works with the latest versions of Mezzanine, but in theory it should work fine. Be advised though, that you should have a solid knowledge of stuff like Django, Git, Virtualenv, pip and Webfaction in general.

**Comment by auvipy** [comment]
you better have a VPS on cloud. better performence and full control over system
