### ISSUE TITLE
Lookup alternative template extensions for different template engines

### ISSUE THREAD

**Issue by destos** [stephenmcd/mezzanine#1279]
I'm in the process of attempting to use jinja2 as the main template renderer for mezzanine and quickly mocked this out to support looking up templates with alternate extensions.

a1d89fc476e4af43fda389a524cfff444d3bc8e4

Initially I created the TemplateList class to be imported into view modules that need create template search hierarchies that are passed to mez.utils.views.render but realized I could just check if the templates passed in are a TemplateList and if not wrap them in it. This performs the previous methodology or checking for a list or tuple and if not wrapping it in a list. With the added benefit of it now retrieving all our desired templates. 

This also adds a new setting `TEMPLATE_EXTENSIONS`, a list of extensions we wish to look up in order of importance which if found will be passed to their respective engines if `TEMPLATES` is configured properly. The only downside of this implementation is it does not introspect `TEMPLATES` for a correct configuration. but as those would differ per engine it may be impossible. 

A potential benefit of this implementation is we would no longer need to specify the template extension anywhere in the views.

I feel this continues the work of a50de50699bb6a24bfb5f118449991aa7608b426 allowing us to create templates individually for differing engines.

Let me know what you think. I'll try to continue working on this today to see if I can actually get jinja2 rendering some templates. I may even create a module in the future for those interested in having a bootstrap base template build in jinja.

**Comment by AlexHill** [comment]
Hi Patrick,

Thanks for working on this.

Short answer: it's neat, but probably won't end up in Mezzanine because it diverges from Django convention too much.

The Django convention is to put jinja2 templates in a ``jinja2`` subdirectory in each app, just as you put DTL templates in ``templates`` – would that work in your case?

Your idea of dispatching on file extension has merit, and was considered by Aymeric Augustin when he implemented 1.8's multiple template engine support ([see the discussion in the DEP](https://myks.org/en/multiple-template-engines-for-django/dep/#engine-selection)).

However, it wasn't adopted, and for that reason we probably won't adopt it in Mezzanine either. Developing with Mezzanine should differ as little as possible from developing with Django. If we diverge from Django in fundamental things like template resolution, we're putting unnecessary obstacles between newcomers and Mezzanine's core features.

I should mention there are certainly parts of Mezzanine that don't adhere to this rule, but I'd like to see their number shrink, not grow. :)

**Comment by destos** [comment]
@AlexHill Thanks for responding. I was mainly hoping to be set in the right direction in regards to template resolution. Which you have done, I'll continue researching django's template changes for a solution. 

Closing.
