### ISSUE TITLE
unicode characters in comments

### ISSUE THREAD

**Issue by Eladio** [stephenmcd/mezzanine#1285]
If I use unicode characters in the username field while submitting a comment an UnicodeEncodeError raises in the set_cookie function. I use Django 1.5 but the issue is also present using the demo page. Encoding the cookie value before passing it to response.set_cookie function would solve the problem.

**Comment by stephenmcd** [comment]
Presumably you mean the name field, since the username field (when signing up for an account) only accepts ascii characters.

I was able to enter non-asii characters fine in this case, see here:

http://cl.ly/auK4

I'll suggest you don't have the correct encoding configured at some layer - the web server, database, shell environment, etc.

**Comment by Eladio** [comment]
Yes, I mean the name field. I used the demo site:

http://mezzanine.jupo.org/blog/

I am still not able to leave comments with unicode charaters in it. Maybe it is an issue of Django version? I don't see any changes in Mezzanine's master branch regarding the comments framework.

**Comment by stephenmcd** [comment]
I'm sorry, my original assessment was incorrect (it's very common). I can reproduce the issue locally (where I know all my encoding knobs to be correct) using Django 1.5 or 1.6, and the current released version of Mezzanine - but when using the development version of Mezzanine with Django 1.7 or 1.8, it's resolved. 

All I can really suggest at this stage is using the development version of Mezzanine with Django 1.8 - it's quite stable and very close to becoming the official next release.
