### ISSUE TITLE
Replace USE_MODELTRANSLATION by adding 'modeltranslation' to INSTALLED_APPS

### ISSUE THREAD

**Issue by wimfeijen** [stephenmcd/mezzanine#1322]
Right now, in order to add django-modeltranslation to INSTALLED_APPS, one needs to set: 

USE_MODELTRANSLATION = True

Instead of adding 'modeltranslation' to INSTALLED_APPS. 

The latter would delete the need for an extra setting, be in line with the way django uses apps, and be less magical. 

Let me know if you agree and I will make a pull request.

**Comment by Kniyl** [comment]
I implemented this feature by following the way USE_SOUTH (now removed) was implemented. I’m not entirely sure about it, but I guess the rationale of using a setting instead of letting the user put the app into INSTALLED_APPS was to clearly show an official support for an optional feature.

For the specific USE_MODELTRANSLATION setting, it is used in various places (mezzanine.core.admin or some templates) and having it explicit makes it easier and “less magical” to rely upon in someone's project or app.

Sure we could change some code in the createdb command to check if modeltranslation is in INSTALLED_APPS and set USE_MODELTRANSLATION accordingly instead of doing it the other way around. But it doesn't quite fit the way I learnt Mezzanine so I’m really unsure about it.

**Comment by stephenmcd** [comment]
I don't have strong opinions either - keen to hear thoughts from more people.

**Comment by stephenmcd** [comment]
I guess in lieu of any strong reasons for keeping it, removing the setting and having things more Django-like is a good case.

I imagine anywhere we actually use `USE_MODELTRANSLATION` could be replaced with checking for it in `INSTALLED_APPS`.
