### ISSUE TITLE
How do I turn off the WYSIWYG editor?

### ISSUE THREAD

**Issue by nikolas** [stephenmcd/mezzanine#1335]
The documentation here (http://mezzanine.jupo.org/docs/admin-customization.html#wysiwyg-editor) says:

> The setting RICHTEXT_WIDGET_CLASS contains the import path to the widget class that will be used for editing each of these fields, which therefore provides the ability for implementing your own editor widget which could be a modified version of TinyMCE, a different editor or even no editor at all.

How do I disable the TinyMCE editor? I think the documentation should make it more obvious how to do this, because I can't figure out the intended way to do this. For example, if I put `RICHTEXT_WIDGET_CLASS = None` in my `settings.py`, I get an error.

I'm using Mezzanine v3.1.10.

**Comment by jerivas** [comment]
Hey Nikolas.

Setting the widget to None is invalid because Mezzanine must have something to render in that field. What you really want to do is tell Mezzanine to use the default `<textarea>` widget, which is located at `django.forms.widgets.TextArea`.

A list of Django's default widgets is available [here](https://docs.djangoproject.com/en/1.6/ref/forms/widgets/).

**Comment by jerivas** [comment]
Sorry, it should be `django.contrib.admin.widgets.AdminTextareaWidget`.

**Comment by nikolas** [comment]
thank you!
