### ISSUE TITLE
modeltranslation migrations created in `site-packages`

### ISSUE THREAD

**Issue by steckerhalter** [stephenmcd/mezzanine#1415]
so when model-translation creates migrations for pages, blog etc. it does that in the mezzanine directory that was installed via pip/virtualenv

could this be due to something I'm doing wrong? 

currently I need to copy them manually to the staging server. they are not in version control like that and I guess they would be deleted if mezzanine would be upgraded

**Comment by steckerhalter** [comment]
looks like this is mentioned at http://mezzanine.readthedocs.org/en/latest/multi-lingual-sites.html#translation-fields-and-migrations

I don't fully understand it yet though

**Comment by jerivas** [comment]
It basically says that you will need to keep your own migrations for the 
apps you want to have translated. With MIGRATION_MODULES you have to 
define were you want Django to look for the migrations of each app. You 
will have to manually run makemigrations if Django or Mezzanine ever 
ship field modifications. Make sure you also read about field injection 
caveats, because the principle is the same: 
http://mezzanine.readthedocs.org/en/latest/model-customization.html#field-injection-caveats.

By the way, please use the mailing list for general questions like this. 
If you still have questions about this topic, open a thread over there. 
Thanks!
