### ISSUE TITLE
URL won't change when switching blog on the navbar

### ISSUE THREAD

**Issue by zruu** [stephenmcd/mezzanine#1467]
I just experienced something that probably is a bug. Maybe you guys already know about it, maybe not.

Mezzanine 4.0.1
Django 1.8.5
Python 2.7.10
MySQL 5.7.9
Darwin 14.5.0

I have setup three blogs:

localhost
b1.localhost
b2.localhost

When for example I am on localhost/admin/conf/setting/ I tried to switch blog on the navbar to change settings e.g. b1.localhost. But the URL wouldn't change (b1.localhost/admin/conf/setting/) so the changes were made to localhost and not b1.localhost when saving.  

`<form action="/set_site/" class="dark-select">`, just to clarify which form is not working properly. 

This issue is not only when trying to change the settings. The navbar switcher won't work overall.

**Comment by stephenmcd** [comment]
This is working as intended, you should probably have a read over the start of:

http://mezzanine.jupo.org/docs/multi-tenancy.html

Some things to note: 

- Site selector in admin won't change the URL being used to access the admin over, it sets a session variable controlling which site data is being used - this is so that the admin can always be access over a single domain which may be the only one containing an SSL certificate.
- If you view the front-end site as a logged-in administrator with the session variable set, that site's data will be used regardless of the host being accessed - this is so that the content administrator can preview their changes, regardless of which host their authenticated session is tied to.
