### ISSUE TITLE
Cannot select image in filebrowser

### ISSUE THREAD

**Issue by lorence-ingenuity** [stephenmcd/mezzanine#1472]
I cannot select an uploaded image if it is using a through many-to-many field and being used as an inline. I used a `FileBrowseField`. It shows a javascript error when clicking the select button.\
```
Uncaught TypeError: Cannot set property 'value' of null
    FileSubmit @ FB_FileBrowseField.js:16
    onclick @ ?pop=1&dir=products:295
```

**Comment by stephenmcd** [comment]
Can you provide a sample project that reproduces this?

**Comment by etionsun** [comment]
The similar issue.

The steps:
1.Create new mezzanine project
2.Create DB
3. Login admin
4.Edit Gallery page
5.Upload images
6.Click add another image link

The new edit line:
 
<a style="padding:5px 16px;" href="javascript:FileBrowser.show('**id_images-__prefix__-file**', '/admin/media-library/browse/?pop=1&amp;dir=galleries&amp;type=Image');" class="fb_show">
    <img src="/static/filebrowser/img/filebrowser_icon_show.gif" alt="">
</a>

The first param is invalid for show function.

**Comment by ryneeverett** [comment]
@etionsun We've fixed similar issues 2 or 3 times since this was opened so I don't think this issue is the appropriate place for your post. However, I'd like to note that the way that first `FileBrowser.show` parameter is generated was [recently changed](https://github.com/stephenmcd/filebrowser-safe/pull/93), so mixing releases and development versions of grappelli-safe, filebrowser-safe, and mezzanine is unlikely to go well; use all latest release or all similarly aged development versions unless you really know what you're doing.
