### ISSUE TITLE
pruning merged branches?

### ISSUE THREAD

**Issue by nyov** [stephenmcd/mezzanine#1496]
Sorry to bother, but I was wondering why you keep around merged branches instead of pruning them? There are over 300 merged and thus outdated branches. It's kinda hard to find the relevant branches that actually have changes not in master, especially with several remotes from other people.

![mezzanine-git](https://cloud.githubusercontent.com/assets/438293/11770672/4df783e8-a1fc-11e5-9264-affb673be87d.gif)

**Comment by stephenmcd** [comment]
Can you post this to the mailing list instead? Thanks

**Comment by nyov** [comment]
Not a google groups user, sorry.

**Comment by stephenmcd** [comment]
Well you'll need to join the group in order to participate. If you have any other questions you'll need to post them there, as we use the issue tracker to maintain a working list of work that needs to be done.

As for the branches, they're not really dealt with here as the Github repo is just a mirror of the main repo here: https://bitbucket.org/stephenmcd/mezzanine
