### ISSUE TITLE
Rename of images in the Media Library doesn't allow to change the name

### ISSUE THREAD

**Issue by michalfita** [stephenmcd/mezzanine#1522]
Every time I upload a photo from my camera I need to rename it to something more informative. Whatever I enter in the field, the error message is displayed:

> Please correct the following errors.
> Only letters, numbers, underscores, spaces and hyphens are allowed.

This is all in Mezzanine 4.1.0.

**Comment by stephenmcd** [comment]
This is working as intended. Please use the mailing list.

**Comment by brejoc** [comment]
@stephenmcd If [this is the correct reference](https://groups.google.com/forum/#!searchin/mezzanine-users/rename/mezzanine-users/R1guSXhYAf0/EroE3T8uYisJ), this bug should not be closed due to multiple reasons:

1. The error message is completely misleading, since there is nothing wrong with **this** filename.
2. During the renaming process Mezzanine should not care about other files than this one (and the file with the target filename).
2. Using dots in the prefix should be allowed by default. It is a pattern seen far too often.
