### ISSUE TITLE
Thumbnail template tag saves thumbnail to MEDIA_URL using urlencoded path

### ISSUE THREAD

**Issue by emenendez** [stephenmcd/mezzanine#1580]
When using the thumbnail template tag in a site which also uses the s3boto file-storage backend to store all media files in an S3-backed CDN, files containing any characters which are urlencoded result in broken thumbnail links. This seems to be because the thumbnail tag code saves the auto-generated thumbnail to S3 using a urlencoded path (https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templatetags/mezzanine_tags.py#L400), but the s3boto backend does not expect this and does not un-encode it. Therefore, files are saved to S3 with with names such as "image-%23fff.png" instead of "image-#fff.png" and links to these files from the pages themselves are broken.

**Comment by AlexHill** [comment]
Looking over the code I think a simple change to the line you linked to should do the job. `thumb_url` is quoted because this is in a template tag, whose output is destined for an `img` element's `href` attribute – saving to S3 was probably added later, and the existing quoted path was used unchanged.

Can you try changing that line to

`default_storage.save(unquote(thumb_url), File(f))`

Let us know how you go.
