### ISSUE TITLE
Problems starting a mezzanine project with Drum installed

### ISSUE THREAD

**Issue by mkevac** [stephenmcd/mezzanine#1746]
Hi, I'm having some problems launching a drum project

When I use this command
```
mezzanine-project -a drum project_name
```

I get this error, regardless of the project_name used:

```
CommandError: 'project_name' conflicts with the name of an existing Python module and cannot be used as a project name. Please try another name.
```

Any thoughts?

Thanks

From here: https://github.com/stephenmcd/drum/issues/51

**Comment by stephenmcd** [comment]
This will occur if you use the same `project_name` twice, since this command creates a Python package on the current path - the second time will conflict.

> I get this error, regardless of the project_name used:

I'm not convinced that's true, and I feel like you're probably entering duplicate names. At least I can't reproduce it. If you're able to shed any further light, please re-open.
