### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by solarissmoke** [stephenmcd/mezzanine#1749]
Django 1.11 is out, and it would be great if we could update Mezzanine to support it. 

I'm happy to work on a PR but wanted to ask whether we can drop support for Django 1.8 at the same time (it makes life a lot easier if we don't have to maintain compatibility)?

**Comment by ryneeverett** [comment]
Sorry but we want to continue supporting 1.8 since it's an LTS version. Our goal is to support all versions of django that are supported by upstream: https://www.djangoproject.com/download/#supported-versions. Looks like we *can* drop support for 1.9 though.

**Comment by solarissmoke** [comment]
Okay, that's fair enough. I have got it working locally, hope to have a PR ready this weekend.

**Comment by stanim** [comment]
Any news?

**Comment by robd003** [comment]
Is anyone else having issues with context not being passed as a dict but rather as RequestContext?

**Comment by stephenmcd** [comment]
@robd003 you'll find the merged PR for 1.11 support deals with that extensively: https://github.com/stephenmcd/mezzanine/pull/1750

**Comment by jpic** [comment]
I think that is good to close until you want to release it first ?

**Comment by keithdechant** [comment]
Is there going to be a new release including this change?

**Comment by ushijimay** [comment]
I am looking forward to the new release, too.

**Comment by you-zhou** [comment]
How could I start a Mezzanine with Cartridge project that uses Python 3.6 + Django 1.11LTS?
Is there a time line to for the new release? Or is it going to be hard to migrate from Mezzanine 4.2.3? Cheers.

**Comment by Beomjun** [comment]
Any updates?

**Comment by stephenmcd** [comment]
**Nothing is stopping you from using Mezzanine with the latest version of Django right now.** Simply specify the latest commit in this git repo as your dependency. This is a very basic task when working with Python, so if you don't know how, searching for "pip git" will yield a wealth of information on the topic.

With that said, please refrain from asking when there will be a new release or if there are any updates. The only update would be that the release has been made. When that happens, this issue will get closed off. If it's still open, that means there hasn't been a release yet. It will happen when I can find the time, which is something that I cannot predict. This is all relatively trivial given the fact you can use Mezzanine with the latest Django version right now.

**Comment by you-zhou** [comment]
Thanks, Stephen.

**Comment by alex-polosky** [comment]
I just wanted to say thank you so much for this code change. I spent a while trying to figure out what was going wrong after I updated to Django 1.11, and then I was able to stumble upon this.

Also my apologies if this is seen as spam. I'm just showing appreciation!

**Comment by jfroejk** [comment]
It would still be great if an official release supporting Django 1.11 could be made. Mezzanine is a great product, I have been using it for years, but to many potential newcomers the project looks "dead" given the fact that there is long between official releases. It would be great if a core team could make releases more often so it wouldn't depend that much on Stephen (who has done an absolutely fabulous job but of cause can't spend unlimited amounts of time on Mezzanine)

**Comment by skru** [comment]
I'd love to get more involved. Always a bit hesitant as i'm hardly a
seasoned developer but feel I owe a lot to Mezzanine and its contributors.

Over the last year I've worked pretty much exclusively with Mezzanine, I've
built some nice features that might be of use to other developers, such as
multiple account and product types that have allowed us to sell digital
products, event tickets, subscriptions and use mezzanine as our primary
accounting database (we send our invoices directly from the site to our
accredited accountants).
I have modified the checkout to fully incorporate Paypal and Stripe (with
different shipping and product options) and to issue unpaid invoices so our
third world customers have a better chance of transferring funds to us via
international bank transfer.

As I said, I'm not the best dev so there would be a lot of work to do to
actually package any of this up, but some of it I'm sure would be of use,
especially the product types.

Is there any interest in adding new features, or would you say I'd be
better off helping with bug fixes etc?

Joe

**Comment by jerivas** [comment]
@skru Contributions are certainly always welcome! I suggest you direct your efforts towards bug fixing and specifically testing. If you can move your projects to Mezzanine master / Django 1.11 (on your local machine first, but perhaps even on production) and check that they work then we can be reasonably sure that no big regressions have been introduced.

**Comment by ryneeverett** [comment]
Completely agree with Ed that testing would be the best contribution toward more frequent releases.

The problem is that we’re currently reliant on manual testing which only a few people have the experience and community trust to do. Others, myself included, CANNOT do the manual testing required to push a release, but we can write automated tests to decrease and perhaps even eliminate this burden once the tests have proven reliable.

If you don’t know where to start, I would suggest looking back at some of the worst bugs in mezzanine history and writing tests that would have caught them. Then think about whether there’s an opportunity to catch entire classes of bugs.

**Comment by jerivas** [comment]
Just to throw more ideas into the hat:

- A Selenium test suite for the admin, testing things like the Rich Text 
editor, drag and drop ordering (pages and inlines), file browser, etc.

- A test class that would hit every URL generated by Mezzanine's sitemap 
and report non-200 response codes. Should be useful for integration 
testing on existing sites after an upgrade, and it would test against 
real Page instances (or everything that has a slug, really).

**Comment by ryneeverett** [comment]
We should add this to the FAQ. Something like “Why haven’t you cut a release recently? Is Mezzanine dead?”

**Comment by jpic** [comment]
Just let Joseph take it from here :joy:

Le 2 févr. 2018 2:37 PM, "ryneeverett" <notifications@github.com> a écrit :

We should add this to the FAQ. Something like “Why haven’t you cut a
release recently? Is Mezzanine dead?”

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stephenmcd/mezzanine/issues/1749#issuecomment-362588277>,
or mute the thread

**Comment by jpic** [comment]
@ed django-responsediff has a one liner to spider the website perhaps that
would help ? It was made for the memopol project by la quadrature but I've
used it in other CMS projects to cheat on coverage and easy python/Django
version updates (which is why your need 100% coverage).
Selenium tests are great but I've had lots of portability issues with it,
for example the small test suite for django-autocomplete-light doesn't pass
on Travis and it's consumed really a lot of my resource fixing concurrency
and it works really well over time with all browsers on my laptop.
But **most importantly** selenium is an excuse to not unit test js, and
maintain the pipeline that goes with it. I'd rather contribute on this that
runs well on a Travis or other shared hardware in the pipeline, and keep
the test run below two minutes, we can always compensate with mocks, this
will have a better ROI in my experience.
I recommend we give root access to Joseph so that he can lead the the way
to make a mezzanine happening in 2018 <3

**Comment by stephenmcd** [comment]
I think we should target Django 2.0 support for the next release.

**Comment by solarissmoke** [comment]
@stephenmcd I had a look at adding Django 2 support some time ago. The main issue I ran into is that other dependencies (primarily `filebrowser_safe` and `grappelli_safe`) are not Django 2 compatible, and changes need to be made there before Mezzanine will work.

There is in my mind a question about whether to still rely on the forks of those packages. I do not now the history of why they were forked but if possible it seems better to rely on the original packages if they are being maintained, rather than having to maintain separate forks.

**Comment by stephenmcd** [comment]
> There is in my mind a question about whether to still rely on the forks of those packages.

We'll still rely on those so they'll need updating.

**Comment by talawahtech** [comment]
The Django team released an update for two security issues today, but that update is not available for 1.10 because it is no longer supported: https://www.djangoproject.com/weblog/2018/mar/06/security-releases/

The update is available for 1.8, 1.11 and 2.0, but 1.8 will become de-supported on Apr 1 (a few weeks from now). 

Any recommendations for someone about to do a brand new Mezzanine deployment this week?

Specific git commit + Django 1.11 vs  specific commit + Django 2.0?

**Comment by jerivas** [comment]
I would go with the latest commit on Master + Django 1.11.

On Mar 6, 2018 1:35 PM, "Marc Richards" <notifications@github.com> wrote:

The Django team released an update for two security issues today, but that
update is not available for 1.10 because it is no longer supported:
https://www.djangoproject.com/weblog/2018/mar/06/security-releases/

The update is available for 1.8, 1.11 and 2.0, but 1.8 will become
de-supported on Apr 1 (a few weeks from now).

Any recommendations for someone about to do a brand new Mezzanine
deployment this week?

Specific git commit + Django 1.11 vs specific commit + Django 2.0?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stephenmcd/mezzanine/issues/1749#issuecomment-370900969>,
or mute the thread

**Comment by simenheg** [comment]
For what it's worth, I've been running Mezzanine master with Django 1.11 in production for a couple of weeks now without any problems (and in development for several months). The only change I had to make was to pull a newer version of filebrowser-safe than the version required by Mezzanine.

**Comment by qcaron** [comment]
Is there any 4.2.4 release planned so we can enjoy installing Mezzanine and use Django 1.11??

**Comment by stephenmcd** [comment]
4.3.0 is now out and supports Django 1.11

**Comment by stephenmcd** [comment]
@qcaron you missed my comment earlier in this thread: https://github.com/stephenmcd/mezzanine/issues/1749#issuecomment-334009914

**Comment by solarissmoke** [comment]
@stephenmcd just FYI filebrowser-safe on pypi doesn't work with Django 1.11 - it's been fixed on master of that repo though. If you are able to push a new release of that, it would mean everything can be installed from Pypi for it to work on Django 1.11.

**Comment by stephenmcd** [comment]
@solarissmoke Thanks, those are up now.

**Comment by stanim** [comment]
The documentation still mentions:

> Django 1.8 to 1.10

http://mezzanine.jupo.org/docs/overview.html#installation

I created a pull request for this: https://github.com/stephenmcd/mezzanine/pull/1863

**Comment by vstoykov** [comment]
Currently when running test suite from master (and `django-filebrowser_safe` also from master) only two tests are failing for Django 2.0/2.1 and current Django master https://travis-ci.org/stephenmcd/mezzanine/builds/432221985.

The root cause of both tests to fail is kind of the same. In Django 2.0+ handling of byte strings in the places where native string should be used is now completely broken. Instead of giving you error or trying to convert to native string it just uses the string representation of byte string (by adding `b'` in front and `'` at the end and escaping all non ASCII characters). This can silently go deep in the stack and strange things can happened.

For one of them I prepared a PR, and the fix is in the test and not in mezzanine itself #1887.

For the second test it's more complicated. It is testing the possibility to set settings in byte string and storing it in DB. This will ultimately not work in Django 2+. From what I see we have the following options:
1. Skip the test for all versions of Django >= 2.0 (easy)
2. Trying to make the functionality to work on Django >= 2.0 (very hard)
3. Something different (I don't know)

**Comment by stephenmcd** [comment]
@vstoykov thanks for all your help - I merged all your changes, please let us know if you think we're 2.0 ready.

**Comment by vstoykov** [comment]
I just added one last PR for fixing the final failing test (by disabling another test under Python 3). You can look at the PR and see if this is ok for the test suite.

Currently I think that Django 2.0 compatibility is ready in the main code base. Just Test suite need to be fixed in order to release new version with all tests passing.

**Comment by stanim** [comment]
Is it also compatible with Django 2.1?

**Comment by vstoykov** [comment]
@stanim yes. Look here https://travis-ci.org/stephenmcd/mezzanine/builds/432399128

**Comment by Allan-Nava** [comment]
Django mezzanine supports Django 2.0 ?

**Comment by manelclos** [comment]
Hi @stephenmcd,

What about moving this project to JazzBand? it looks that several people are doing the same job trying to fix the code to make it work in newer versions of Django. Just a couple: https://github.com/fermorltd/mezzanine/commits/2.2-compat and https://github.com/khadegd/august/commits/dev

As expected those efforts have no commits in the last two months. It is really difficult for people using Mezzanine decide what to do next: start using one of the forks or move to another platform.

Could you please provide some insight about your plans for Mezzanine?

Thanks in advance!

**Comment by jerivas** [comment]
#1956 implements support for Django 2.2, the current LTS
