### ISSUE TITLE
SVG uploads do not work properly in media library.

### ISSUE THREAD

**Issue by heluca** [stephenmcd/mezzanine#1794]
Upload any SVG file, it will look like it succeeded, but the image preview will be broken.  Clicking the image results in an XML parsing error.  The file will be about 500 bytes instead of several kb.  
Example:
http://mezzanine.jupo.org/static/media/uploads/instagram-logo.svg
Source file:
https://www.flaticon.com/free-icon/instagram-logo_69366#

This works properly on Mezzanine 3.1.10

**Comment by matsjoyce** [comment]
This seems to be connected to filebrowser. If I add:

```py3
FILEBROWSER_ESCAPED_EXTENSIONS = []
```

to my `settings.py`, the problem goes away.

**Comment by stephenmcd** [comment]
This is a security feature - since SVG is markup that can contain exploitable scripting, it's escaped in the same way uploaded HTML content is. You'll need to add the relevant tags and attributes to their respective settings that control what gets filtered. See http://mezzanine.jupo.org/docs/frequently-asked-questions.html#why-does-the-wysiwyg-editor-strip-out-my-custom-html
