### ISSUE TITLE
library django-contrib-comments breaks Django 1.8-1.10 support

### ISSUE THREAD

**Issue by mathemaat** [stephenmcd/mezzanine#1903]
According to the docs Mezzanine is supposed to support Django versions 1.8-1.11. Unfortunately versions 1.8 up to 1.10 are no longer supported, since `django-contrib-comments`, one of Mezzanine's dependencies, released [version 1.9.0](https://pypi.org/project/django-contrib-comments) this August, which (out of the 1.* series) only supports 1.11.

**Comment by mathemaat** [comment]
My set-up is Django 1.8 with Mezzanine 4.2.3, so if a new version 4.2.4 could address this issue, then I am very grateful.

My intention was to upgrade to Django 1.11 step by step (i.e. first 1.9 and 1.10). Taking the leap from 1.8 to 1.11 would also be an option, but I prefer following up on my original idea, as I think it's good practice.

**Comment by jerivas** [comment]
We need to cleanup the supported Django versions on Mezzanine, because we only plan to support whatever Django versions are supported. That means 1.8, 1.9, 1.10, and 2.0 are not supported at the time of this comment.

Aside from that, my strategy to maintain Mezzanine sites has been to stick to the Django LTS releases. I suggest you upgrade from 1.8 to 1.11, since very little has changed.
